name: ci

on:
  push:
    branches: [main, master]
    tags: ["v*"]
    paths:
      - "**/*.ml"
      - "**/*.opam"
      - "**/*.opam.locked"
      - "**/dune"
      - "dune-project"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**/*.ml"
      - "**/*.opam"
      - "**/*.opam.locked"
      - "**/dune"
      - "dune-project"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2.0"
      - run: opam install . --deps-only --with-test --locked -y
      - run: opam exec -- dune test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: otk-linux-x86_64
          - os: macos-latest
            artifact: otk-darwin-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2.0"
      - run: opam install . --deps-only --locked -y
      - run: opam exec -- dune build
      - run: cp _build/default/bin/main.exe ${{ matrix.artifact }}
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact }}
